### ISSUE TITLE
vctk dataset training reproduction of repo

### ISSUE THREAD

**Issue by I8dNLo** [p0p4k/vits2_pytorch#47]
Can you please specify the way to reproduce training on vctk dataset?
I've downsampled all the .wavs and even changed naming:
`p362_074_mic1.wav -> p362_074.wav

But something is wrong. For example your script looks for p362_073.wav, but nothing similar exists in original dataset

**Comment by I8dNLo** [comment]
It could also be helpful to provide better instructions for learning with my own dataset. Like the structure of files, structure of key files and setups of env

**Comment by AWAS666** [comment]
> Can you please specify the way to reproduce training on vctk dataset? I've downsampled all the .wavs and even changed naming: `p362_074_mic1.wav -> p362_074.wav
> 
> But something is wrong. For example your script looks for p362_073.wav, but nothing similar exists in original dataset

As the training data has been copied over from vits1, I assume it has been used on an older version of the vctk dataset and the newer one has a handful of files missing (~500).

I'm doing some training on vctk myself and had to clean those up, but didn't want to commit them because it might not be compatible with the new vctk dataset.

**Comment by I8dNLo** [comment]
Can you put it in some other branch for example? The current instruction is misleading and only confuses potential users

**Comment by AWAS666** [comment]
I made #48, there you can check my 3 files.

You can just download them and have your config.json point to those instead of the original, that's how I do it at least.

**Comment by p0p4k** [comment]
merged in latest patch
